version: "3"
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:cached
      - ./src:/var/www/src:cached
    ports:
      - 8081:80
  phpfpm:
    build: ./docker/php
    volumes:
      - ./src:/var/www/src:cached
    env_file:
      ./docker/php/env/develop.env
    ports:
      - "3000:3000"
      - "3001:3001"
  mysql:
    image: mysql:8.0.16
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:delegated
      - ./docker/mysql/log:/var/log/mysql:delegated
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:consistent
    env_file:
      ./docker/mysql/env/develop.env
    ports:
      - 13306:3306
  redis:
    restart: always
    image: redis:5.0.5
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./redis:/data:delegated
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes
